root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/app ./cmd/api"
bin = "./bin/app"
full_bin = "./bin/app"
delay = 200
include_ext = ["go","tpl","tmpl","html","yaml","yml","toml","json"]
exclude_dir = ["vendor","bin","tmp","scripts/migrations"]

[log]
time = true


